# Generated by Django 2.0.2 on 2020-01-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('posted_time', models.TimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=1000)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
